CREATE TABLE contact (
  contact_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id integer REFERENCES user_profile(user_id),
  email VARCHAR NOT NULL,
  phone VARCHAR(30),
  city VARCHAR(255),
  country VARCHAR(255)
);