CREATE TABLE user_profile (
  user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR,
  --because we will use sha-512 hashing algorithm
  email VARCHAR NOT NULL,
  first_name VARCHAR,
  last_name VARCHAR
);